---
title: "Final Infection LSTM"
author: "Tiffany Le"
date: "2026-2-10"
output: pdf_document
---

Activation functions: sigmoid, tanh, ReLu

```{r, message = FALSE}
library(readxl)
```

```{r}
infections <- read_excel("Data/Infections.xlsx")
infections$date <- as.Date(infections$date)
```

```{r}
infections$day <- as.numeric(infections$date - as.Date("2019-11-30"))
infections$fog <- as.factor(infections$fog)
infections$thunder <- as.factor(infections$thunder)
infections$dust <- as.factor(infections$dust)
infections$smoke <- as.factor(infections$smoke)
infections$estpos <- ifelse(infections$posencounters == 0, 0, (infections$posencounters / infections$restests) * infections$encounters)

lancet <- infections[,c(6, 4, 2, 20, 21, 32, 33)]
lancet <- lancet %>%
  arrange(day) %>%
  mutate(
    estpos = rollmean(estpos, k = 30, fill = NA, align = "right"),
    maxtemp = as.numeric(scale(rollmean(maxtemp, k = 30, fill = NA, align = "right"))),
    precip = as.numeric(scale(rollmean(precip, k = 30, fill = NA, align = "right"))),
    wind = as.numeric(scale(rollmean(wind, k = 30, fill = NA, align = "right"))),
    pm10 = as.numeric(scale(rollmean(pm10, k = 30, fill = NA, align = "right"))),
    pm2.5 = as.numeric(scale(rollmean(pm2.5, k = 30, fill = NA, align = "right"))),
  )
lancet <- na.omit(lancet)
```

```{r}
run_ccf <- function(predictor, max_lag = 365) {
  ccf(infections$estpos, predictor, lag.max = max_lag, plot = TRUE)
}

run_ccf(infections$fog)
```

```{r}
get_ccf_info <- function(target, predictor, max_lag = 365) {
  cc <- ccf(target, predictor, lag.max = max_lag, plot = FALSE)
  sig <- 2 / sqrt(length(target))
  idx <- which.max(abs(cc$acf))
  list(
    lag = cc$lag[idx],
    correlation = cc$acf[idx],
    significant = abs(cc$acf[idx]) > sig
  )
}

sub <- na.omit(infections[, names(infections)[!names(infections) %in% c("date", "encounters", "ordtests", "restests", "posencounters", "rdordtests", "rdrestests", "rdposencounters", "posrate", "day", "fog",
"thunder", "dust", "smoke")]])

var <- names(infections)[!names(infections) %in% c("date", "encounters", "ordtests", "restests", "posencounters", "rdordtests", "rdrestests", "rdposencounters", "posrate", "day", "fog",
"thunder", "dust", "smoke")]

results <- lapply(var, function(v) {
  info <- get_ccf_info(sub$estpos, sub[[v]])
  data.frame(
    variable = v,
    lag = info$lag,
    correlation = info$correlation,
    significant = info$significant
  )
})

lvar <- names(lancet)[!names(lancet) %in% c("day", "estpos")]

roll <- lapply(lvar, function(v) {
  info <- get_ccf_info(lancet$estpos, lancet[[v]])
  data.frame(
    variable = v,
    lag = info$lag,
    correlation = info$correlation,
    significant = info$significant
  )
})

results <- do.call(rbind, results)
roll <- do.call(rbind, roll)

roll
```


