---
title: "Infection Join"
author: "Tiffany Le"
date: "2025-09-14"
output: pdf_document
---

```{r}
library(readxl)
library(dplyr)
```

```{r}
env <- read.csv("Environmental.csv")
bucs_2020 <- read_excel("BUCS J18 2020.xlsx", col_types = "guess")[c(-388, -399),]
bucs_2021 <- read_excel("BUCS J18 2021.xlsx")[c(-387, -398),]
bucs_2022 <- read_excel("BUCS J18 2022.xlsx")[c(-387, -398),]
bucs_2023 <- read_excel("BUCS J18 2023.xlsx")[c(-387, -398),]
bucs_2024 <- read_excel("BUCS J18 2024.xlsx")[c(-388, -399),]
```

```{r}
#do not run cell, code not used :)

env$date <- as.Date(env$date, format = "%m/%d/%Y")
bucs_2020$Date <- as.Date(as.numeric(bucs_2020$Date), origin = "1899-12-30")
bucs_2021$Date <- as.Date(as.numeric(bucs_2021$Date), origin = "1899-12-30")
bucs_2022$Date <- as.Date(as.numeric(bucs_2022$Date), origin = "1899-12-30")
bucs_2023$Date <- as.Date(as.numeric(bucs_2023$Date), origin = "1899-12-30")
bucs_2024$Date <- as.Date(as.numeric(bucs_2024$Date), origin = "1899-12-30")
```

```{r}
names(env)[names(env) == "date"] <- "Date"
```

```{r}
infections <- rbind(bucs_2020, bucs_2021, bucs_2022, bucs_2023, bucs_2024)
infections <- infections %>% distinct()
infections <- merge(env, infections, by = "Date")
```

```{r}
names(infections)[c(1, 24:31)] <- c("date", "encounters", "ordtests", "restests", "posencounters", "rdordtests", "rdrestests", "rdposencounters", "posrate")
```

```{r}
infections$posrate <- as.numeric(gsub("%", "", infections$posrate)) / 100
```

```{r}
write.csv(infections, "Infections.csv", row.names = FALSE)
```
